"""<descriptive message>

Revision ID: 1f182148f4fb
Revises: 2ed3e1424ff1
Create Date: 2023-12-12 02:09:00.299404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f182148f4fb'
down_revision = '2ed3e1424ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dish_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_favorites_dish_id_dishes'), 'dishes', ['dish_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_favorites_dish_id_dishes'), type_='foreignkey')
        batch_op.drop_column('dish_id')

    # ### end Alembic commands ###
