"""<descriptive message>

Revision ID: 2ed3e1424ff1
Revises: f7021330fda2
Create Date: 2023-12-12 01:59:12.351675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed3e1424ff1'
down_revision = 'f7021330fda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('fk_favorites_dish_id_dishes', type_='foreignkey')
        batch_op.drop_column('dish_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dish_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_favorites_dish_id_dishes', 'dishes', ['dish_id'], ['id'])

    # ### end Alembic commands ###
