"""<descriptive message>

Revision ID: 75670692920e
Revises: 6af4538eac56
Create Date: 2023-12-08 05:55:53.743438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75670692920e'
down_revision = '6af4538eac56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_dishes_menu_id_menus'), 'menus', ['menu_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_dishes_menu_id_menus'), type_='foreignkey')
        batch_op.drop_column('menu_id')

    # ### end Alembic commands ###
